name: CI
on:
  workflow_call:
    inputs:
      runner_tag:
        description: 'Tag of the specific runner to be used'
        type: string
        default: self-hosted
        required: false
      profile:
        type: string
        description: "Profile for conan"
        default: "default"
jobs:
  build:
    runs-on:  ${{ inputs.runner_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Conan
        run: pip install conan

      - name: Install CMake
        run: sudo apt-get install -y cmake

      - name: Create Conan profile
        run: |
          #conan profile new default --detect
          #conan profile update settings.compiler.libcxx=libstdc++11 default

      - name: Install dependencies
        run: conan install . --profile default --install-folder=build

      - name: Configure CMake
        run: cmake . -Bbuild

      - name: Build the project
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build

jobs:
  build:
    runs-on:  ${{ inputs.runner_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Conan install
        uses: conan-io/conan-action@v3
        with:
          profile: ${{ inputs.profile }}

      - name: Conan build
        uses: conan-io/conan-action@v3
        with:
          args: build --build missing
          profile: ${{ inputs.profile }}
        

      - name: Conan test
        uses: conan-io/conan-action@v3
        with:
          args: test --build missing
          profile: ${{ inputs.profile }}
